//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ClassicWizard.rc
//
#define IDD_WIZ97_WELCOME               115
#define IDD_WIZ97_COMPLETION            116
#define IDD_DLG_LICENSE_AGREE           120
#define IDD_DLG_READ_ME                 121
#define IDD_DLG_ADDITIONAL_INFORMAION   122
#define IDD_DLG_APP_FOLDER              123
#define IDD_DLG_ADDITIONAL_TASK         124
#define IDD_DLG_READY_TO_INSTALL        125
#define IDD_DLG_ALREADY_INSTALLED       126
#define IDD_DIALOG_DOWNLOADER           208
#define IDB_WIZ97_HEADER                1000
#define IDB_WIZ97_WATERMARK             1001
#define IDC_PROGRESS_DOWNLOADING        1001
#define IDC_STATIC_DOWN_PREREQUISITE    1002
#define IDC_BUTTON_ABORT_DOWNLOAD       1003
#define IDC_WIZ97_EXTERIOR_TITLE        1004
#define IDC_WIZ97_EXTERIOR_DESC         1005
#define IDC_WIZ97_WELCOME_NOTAGAIN      1006
#define IDC_WIZ97_SUMMARY               1007
#define IDC_WIZ97_EXTERIOR_CLICKFINISH  1008
#define IDC_WIZ97_BULLET1               1011
#define IDC_WIZ97_BULLET2               1012
#define IDC_WIZ97_BULLET3               1013
#define IDC_WIZ97_BULLET4               1014
#define IDC_WIZ97_BULLET5               1015
#define IDC_WIZ97_BULLET6               1016
#define IDC_WIZ97_BULLET7               1017
#define IDC_WIZ97_BULLET8               1018
#define IDC_WIZ97_BULLET9               1019
#define IDC_RADIO_INSTALL_PRODUCT_FOR_CURRENT_USER 1020
#define IDC_WIZ97_BULLET1_DESC          1021
#define IDC_RADIO_INSTALL_PRODUCT_FOR_ALL_USERS 1021
#define IDC_WIZ97_BULLET2_DESC          1022
#define IDC_WIZ97_BULLET1_DESC2         1022
#define IDC_WIZ97_BULLET1_DESCIPTION    1022
#define IDC_WIZ97_BULLET3_DESC          1023
#define IDC_WIZ97_BULLET4_DESC          1024
#define IDC_WIZ97_BULLET5_DESC          1025
#define IDC_WIZ97_BULLET6_DESC          1026
#define IDC_WIZ97_BULLET7_DESC          1027
#define IDC_WIZ97_BULLET8_DESC          1028
#define IDC_WIZ97_BULLET9_DESC          1029
#define IDC_LABEL_DESCRIPTION           1101
#define IDC_BTN_ADD                     1121
#define IDC_BTN_REMOVE                  1122
#define IDC_LABEL_FILENAME              1207
#define IDC_CHECK_WIZ97_LIC_AGREEMENT   1208
#define IDC_LABEL_FILENAME2             1208
#define IDC_LABEL_CUSTOM_COMBOBOX       1208
#define IDC_EDIT_WIZ97_LICAGREE         1209
#define IDC_LABEL_FILENAME3             1209
#define IDC_LABEL_SEL_COMPONENTS        1209
#define IDC_EDIT_WIZ97_READ_ME          1210
#define IDC_LABEL_SEL_COMPONENTS_DESCRIPTION 1210
#define IDC_EDIT_DEST_FOLDER            1211
#define IDC_BTN_FOLDER_BROWSE           1212
#define IDC_EDIT_WIZ97_INSALL_DETAIL    1213
#define IDC_PROG_INSTALL                1214
#define IDC_EDIT_USER_NAME              1215
#define IDC_EDIT_USER_EMAIL             1216
#define IDC_EDIT_COMPANY                1217
#define IDC_EDIT_CUSTOM_FIELD           1218
#define IDC_EDIT_SERIAL_NUMBER          1219
#define IDC_STATIC_USER_NAME            1220
#define IDC_STATIC_USER_EMAIL           1221
#define IDC_STATIC_COMPANY              1222
#define IDC_STATIC_CUSTOM_FIELD         1223
#define IDC_STATIC_SERIAL_NUMBER        1224
#define IDC_STATIC_WELCOME_COPYRIGHT    1225
#define IDC_STATIC_WELCOME_TITLE        1226
#define IDC_STATIC_WELCOME_PRODUCT      1227
#define IDC_COMBO_CUSTOM_CBMBOX         1228
#define IDC_COMBO_CUSTOM_COMBOBOX       1228
#define IDC_LIST_SELECT_COMPONENTS      1229
#define IDC_CHECK1                      1230
#define IDC_CHECK_CHECK_BOX             1230
#define IDC_CHECK_FINISH_LAUNCH_APPLICATION 1230
#define IDC_SYSLINK1                    1231
#define IDC_SYSLINK_COMPANY             1231
#define IDC_CHECK_FINISH_CUSTOM_ACTION  1231
#define IDC_STATIC_REQUIRED_FREE_SPACE  1232
#define IDC_STATIC_AVAILABLE_SPACE      1233
#define IDC_CHECK_CREATE_SHORTCUTS_IN_START_MENU 1234
#define IDC_CHECK_CREATE_SHORTCUTS_ON_DESKTOP 1235
#define IDC_COMBO1                      1237
#define IDC_COMBO_PROGRAM_GROUP_NAME    1237
#define IDC_WIZ97_EXTERIOR_DESC_COMPLETE 1238
#define IDC_RADIO_ALREADY_INSTALLED_REPAIRE 1239
#define IDC_RADIO_ALREADY_INSTALLED_REPAIR 1239
#define IDC_RADIO_ALREADY_INSTALLED_UNINSTALL 1240
#define IDC_PROGRESS_READY_INSTALLED    1241
#define IDC_PROGRESS_ALREADY_INSTALLED  1241
#define IDC_STATIC_ALREADY_INSTALLED_STS 1242
#define IDC_STATIC_ALREADY_INSTALLED_NOTICE 1243

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1244
#define _APS_NEXT_SYMED_VALUE           201
#endif
#endif
